name: todo_app
description: A simple todo app with BLoC pattern

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true